apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: connect
  name: connect
spec:
  replicas: 1
  selector:
    matchLabels:
      service: connect
  template:
    metadata:
      labels:
        service: connect
    spec:
      containers:
      - env:
        - name: BOOTSTRAP_SERVERS
          value: kafka-0.kafka.default.svc.cluster.local:9092
        - name: CONFIG_STORAGE_TOPIC
          value: my_connect_configs
        - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
          value: http://schema-registry-0.schema-registry.default.svc.cluster.local:8081
        - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
          value: http://schema-registry-0.schema-registry.default.svc.cluster.local:8081
        - name: GROUP_ID
          value: "1"
        - name: INTERNAL_KEY_CONVERTER
          value: org.apache.kafka.connect.json.JsonConverter
        - name: INTERNAL_VALUE_CONVERTER
          value: org.apache.kafka.connect.json.JsonConverter
        - name: KEY_CONVERTER
          value: io.confluent.connect.avro.AvroConverter
        - name: OFFSET_STORAGE_TOPIC
          value: my_connect_offsets
        - name: STATUS_STORAGE_TOPIC
          value: my_connect_statuses
        - name: VALUE_CONVERTER
          value: io.confluent.connect.avro.AvroConverter
        image: gcr.io/[PROJECT_ID]/connect
        name: connect
        ports:
        - containerPort: 8083
        volumeMounts:
        - mountPath: /secrets
          name: service-account-creds
          readOnly: true
        - mountPath: /config
          name: connector-source
      volumes:
      - name: service-account-creds
        secret:
          secretName: service-account-creds
      - name: connector-source
        configMap:
          name: connector-source

