apiVersion: v1
kind: Service
metadata:
  labels:
    service: schema-registry
  name: schema-registry
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  clusterIP: None
  selector:
    service: schema-registry
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: schema-registry
  name: schema-registry
spec:
  serviceName: schema-registry
  replicas: 1
  selector:
    matchLabels:
      service: schema-registry
  template:
    metadata:
      labels:
        service: schema-registry
    spec:
      containers:
      - env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: schema-registry-0.schema-registry.default.svc.cluster.local
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: zookeeper-0.zookeeper.default.svc.cluster.local:2181
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://schema-registry-0.schema-registry.default.svc.cluster.local:8081
        image: confluentinc/cp-schema-registry
        name: schema-registry
        ports:
        - containerPort: 8081
